name = "LibCURL2"
uuid = "a9341e5c-07f0-4893-8fea-80ee6f4ebcc7"
authors = ["Samarin Aleksei <liotbiu1@gmail.com> and contributors"]
version = "2.0.1-DEV"

[deps]
LibCURL2_jll = "e0c91b13-f409-526f-9b5b-50444cc01a73"
MozillaCACerts_jll = "14a3606d-f60d-562e-9121-12d972cd8159"

[compat]
julia = "1"
LibCURL2_jll = "8.2.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
