name = "LibCURL2"
uuid = "a9341e5c-07f0-4893-8fea-80ee6f4ebcc7"
authors = ["Samarin Aleksei <liotbiu1@gmail.com> and contributors"]
version = "1.1.4-DEV"

[deps]
LibCURL_jll = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"
MozillaCACerts_jll = "14a3606d-f60d-562e-9121-12d972cd8159"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
